---
kind: pipeline
name: default

steps:
- name: ttsimport
  image: plugins/docker
  settings:
    repo: ldericher/ttsimport
    auto_tag: true
    dockerfile: ./Dockerfile
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
